---
- name: Enable NX-API before any other tasks
  hosts: nx
  gather_facts: no

  tasks:

  - name: Enable NXAPI access with default configuration
    nxos_nxapi:
      state: present
      enable_http: yes
      enable_https: yes


