---
- name: Gather information about nxos device
  hosts: nx
  gather_facts: no

  tasks:

  - name: Gather facts (ops)
    when: ansible_network_os == 'nxos'
    nxos_facts:
      gather_subset: all
      
  - name: Version is too old
    when: ansible_net_version < target_version
    debug: msg="Version {{ansible_net_version}} is older than {{target_version}}"

  - name: Version is too new
    when: ansible_net_version > target_version
    debug: msg="Version {{ansible_net_version}} is newer than {{target_version}}"

  - name: Display current OS version
    when: ansible_net_version == target_version
    debug: msg="Version {{ansible_net_version}} is already at current target version"

  - name: Copy correct NXOS binary to switch if version is not correct
    when: ansible_net_version != target_version
    nxos_file_copy: 
      local_file: "9.2.2.txt"
      remote_file: "9.2.2.txt"
      file_system: "bootflash:"
