---
- name: Check if devices match the Gold config
  hosts: nx
  gather_facts: no

  tasks:
  - name: Check gold config status
    nxos_config:
      lines:
        - clock timezone PST 8 0
        - logging timestamp milliseconds
        - no ip source-route
      backup: yes
    when: ansible_network_os == 'nxos'

  - name: Set domain attributes
    nxos_system:
      domain_lookup: False
      domain_name: "{{domain_name}}"

  - name: Set standard logging settings
    nxos_logging:
      aggregate:
        - { dest: console, dest_level: 7 }
        - { dest: logfile, dest_level: 6, name: mylog }
      state: present

  - name: Enable standard features
    loop:
      - scp-server
      - sftp-server
      - interface-vlan
    nxos_feature:
      feature: "{{item}}"
      state: enabled

  - name: Configure VTY and console
    when: ansible_network_os == 'nxos'
    loop: 
      - line vty
      - line console
    nxos_config:
      lines:
        - exec-timeout 525600
      parents: "{{ item }}"

  - name: Set NTP
    when: ansible_network_os == 'nxos'
    loop: "{{ ntp_servers }}"
    nxos_config:
      lines:
        - ntp server {{ item }} use-vrf default

  - name: Create temp user
    when: ansible_network_os == 'nxos'
    nxos_config:
      lines:
        - username deleteme password C1sco12345 role network-admin


