---
- name: Check if devices have all expected users, and purge any extra users
  hosts: nx
  gather_facts: no

  tasks:
  - name: Create local device users
    nxos_user:
      aggregate:  "{{ local_users_full }}"
      state: present
      purge: yes
      update_password: on_create
